language: node_js

git:
  depth: 3

matrix:
  - node_js: "6"
    env: SCRIPT=test:unit
  - node_js: "6"
    env: NODE_SCRIPT=./tests/run_e2e.js
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: SCRIPT=test:unit
  - node_js: "8"
    env: NODE_SCRIPT=./tests/run_e2e.js
  - node_js: "8"
    env: SCRIPT=protractor:ci

preinstall:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

postinstall:
  - sudo /etc/init.d/xvfb start
  - export DISPLAY=:99
  - sleep 3
  - fluxbox &

test:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node ./$NODE_SCRIPT; fi
