environment:
  matrix:
    - nodejs_version: "7"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint && npm run test:unit && node tests/run_e2e.js

build: off

cache:
  - node_modules
