language: node_js

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null

matrix:
  fast_finish: true
  include:
    - node_js: "6"
      os: linux
      env: SCRIPT=lint
    - node_js: "6"
      os: linux
      env: SCRIPT=test:unit
    - node_js: "6"
      os: linux
      env: NODE_SCRIPT=tests/run_e2e.js
    - node_js: "8"
      os: linux
      env: NODE_SCRIPT=tests/run_e2e.js
    - node_js: "6"
      os: osx
      env: NODE_SCRIPT=tests/run_e2e.js
    - node_js: "8"
      os: osx
      env: NODE_SCRIPT=tests/run_e2e.js

before_install:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node $NODE_SCRIPT; fi
